export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const GET_TOP_PRODUCT_SUCCESS = 'GET_TOP_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
export const GET_LIST_PRODUCT_DETAIL = 'GET_LIST_DATA_DETAIL';
// export const GET_RELATED_DATA = 'GET_REALATED_DATA';
export const GET_DATA_ERROR = 'GET_DATA_ERROR';


export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';


export const ADD_CART = 'ADD_CART';
export const UPDATE_CART = 'UPDATE_CART';



export const HISTORY_ORDER = 'HISTORY_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART';


export const DETAIL_BILL = 'DETAIL_BILL';

export const CHAT = 'CHAT';